version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db-1
    restart: always
    environment:
      POSTGRES_DB: sgrh
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build: .
    container_name: web-1
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000

volumes:
  pgdata:
