"""add cempo data fim no capacitações

Revision ID: 0190df812c20
Revises: ec3ff682bcb6
Create Date: 2025-05-05 12:54:52.283569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0190df812c20'
down_revision = 'ec3ff682bcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_fim', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacitacao', schema=None) as batch_op:
        batch_op.drop_column('data_fim')

    # ### end Alembic commands ###
