"""Renomear resultado para observacao na tabela exame

Revision ID: 097b845495d1
Revises: c196921b86ca
Create Date: 2025-05-22 15:05:31.418045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097b845495d1'
down_revision = 'c196921b86ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))
        batch_op.drop_column('resultado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resultado', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###
