"""alterado PessoFolha id

Revision ID: 295f0f24f4cf
Revises: ee75417bdbb7
Create Date: 2025-05-06 19:07:37.407110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295f0f24f4cf'
down_revision = 'ee75417bdbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
