"""remove doenca table

Revision ID: 31da7f919933
Revises: ae959877ab1f
Create Date: 2025-05-05 11:51:54.095604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31da7f919933'
down_revision = 'ae959877ab1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doenca', schema=None) as batch_op:
        batch_op.drop_index('ix_doenca_pessoa_id')

    op.drop_table('doenca')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doenca',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pessoa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cid', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_diagnostico', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], name='doenca_pessoa_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='doenca_pkey')
    )
    with op.batch_alter_table('doenca', schema=None) as batch_op:
        batch_op.create_index('ix_doenca_pessoa_id', ['pessoa_id'], unique=False)

    # ### end Alembic commands ###
