"""corrigido relacionamentos com overlaps

Revision ID: 3abf98a34910
Revises: ea603b00e98a
Create Date: 2025-05-06 17:43:27.500146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abf98a34910'
down_revision = 'ea603b00e98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
