"""add tabela lotacao

Revision ID: 5233c47a47ad
Revises: 31da7f919933
Create Date: 2025-05-05 12:11:24.932212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5233c47a47ad'
down_revision = '31da7f919933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotacao_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lotacao_setor_id'), ['setor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotacao_setor_id'))
        batch_op.drop_index(batch_op.f('ix_lotacao_pessoa_id'))

    op.drop_table('lotacao')
    # ### end Alembic commands ###
