"""Migração inicial

Revision ID: 5fa785470263
Revises: 
Create Date: 2025-06-26 17:40:59.627213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa785470263'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exame_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('risco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('risco_exame_catalogo',
    sa.Column('risco_id', sa.Integer(), nullable=False),
    sa.Column('exame_catalogo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exame_catalogo_id'], ['exame_catalogo.id'], ),
    sa.ForeignKeyConstraint(['risco_id'], ['risco.id'], ),
    sa.PrimaryKeyConstraint('risco_id', 'exame_catalogo_id')
    )
    op.create_table('setor_risco',
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('risco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['risco_id'], ['risco.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('setor_id', 'risco_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setor_risco')
    op.drop_table('risco_exame_catalogo')
    op.drop_table('risco')
    op.drop_table('exame_catalogo')
    # ### end Alembic commands ###
