"""Criação inicial das tabelas com observacao

Revision ID: 79694db40bfe
Revises: 
Create Date: 2025-06-11 21:48:01.100339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79694db40bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atestado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.String(length=200), nullable=False))
        batch_op.drop_column('motivo')

    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))
        batch_op.drop_column('resultado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resultado', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('observacao')

    with op.batch_alter_table('atestado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###
