"""Adiciona tabela Curso e ajusta Capacitacao

Revision ID: 92efd982d0e8
Revises: 4bcdaa5d060a
Create Date: 2025-04-15 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92efd982d0e8'
down_revision = '4bcdaa5d060a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_capacitacao_curso', 'curso', ['curso_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacitacao', schema=None) as batch_op:
        batch_op.drop_constraint('fk_capacitacao_curso', type_='foreignkey')
        batch_op.drop_column('curso_id')

    # ### end Alembic commands ###
