"""corrigido relacionamentos com overlaps adicionais

Revision ID: 9560e9b43352
Revises: dba2faf92e39
Create Date: 2025-05-06 17:48:29.251969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9560e9b43352'
down_revision = 'dba2faf92e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
