"""ajuste data fim no capacitacoes

Revision ID: 9cfd84b28acd
Revises: 0190df812c20
Create Date: 2025-05-05 12:57:25.055380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfd84b28acd'
down_revision = '0190df812c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
