"""alterado relacionamento folha para usar classe PessoaFolha

Revision ID: a8868105d9f4
Revises: b589595603b6
Create Date: 2025-05-06 16:52:28.796067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8868105d9f4'
down_revision = 'b589595603b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa_folha',
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('folha_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['folha_id'], ['folha.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('pessoa_id', 'folha_id')
    )
    with op.batch_alter_table('folha', schema=None) as batch_op:
        batch_op.drop_index('ix_folha_pessoa_id')
        batch_op.drop_constraint('folha_pessoa_id_fkey', type_='foreignkey')
        batch_op.drop_column('valor')
        batch_op.drop_column('pessoa_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pessoa_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('folha_pessoa_id_fkey', 'pessoa', ['pessoa_id'], ['id'])
        batch_op.create_index('ix_folha_pessoa_id', ['pessoa_id'], unique=False)

    op.drop_table('pessoa_folha')
    # ### end Alembic commands ###
