"""empty message

Revision ID: ae959877ab1f
Revises: 4438b40c1595
Create Date: 2025-04-25 12:14:59.196448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae959877ab1f'
down_revision = '4438b40c1595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
