"""Add unique constraints and indexes

Revision ID: b30b2f1f8e18
Revises: f2617da78c90
Create Date: 2025-04-23 11:59:46.484259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30b2f1f8e18'
down_revision = 'f2617da78c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacitacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capacitacao_curso_id'), ['curso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capacitacao_pessoa_id'), ['pessoa_id'], unique=False)

    with op.batch_alter_table('doenca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doenca_pessoa_id'), ['pessoa_id'], unique=False)

    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exame_pessoa_id'), ['pessoa_id'], unique=False)

    with op.batch_alter_table('folha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folha_pessoa_id'), ['pessoa_id'], unique=False)

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoa_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_pessoa_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_pessoa_matricula'), ['matricula'], unique=True)

    with op.batch_alter_table('profissao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profissao_nome'), ['nome'], unique=True)

    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setor_nome'), ['nome'], unique=True)

    with op.batch_alter_table('termo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_termo_pessoa_id'), ['pessoa_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    with op.batch_alter_table('vacina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacina_pessoa_id'), ['pessoa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacina_pessoa_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    with op.batch_alter_table('termo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_termo_pessoa_id'))

    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setor_nome'))

    with op.batch_alter_table('profissao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profissao_nome'))

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoa_matricula'))
        batch_op.drop_index(batch_op.f('ix_pessoa_email'))
        batch_op.drop_index(batch_op.f('ix_pessoa_cpf'))

    with op.batch_alter_table('folha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folha_pessoa_id'))

    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exame_pessoa_id'))

    with op.batch_alter_table('doenca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doenca_pessoa_id'))

    with op.batch_alter_table('capacitacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capacitacao_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_capacitacao_curso_id'))

    # ### end Alembic commands ###
