"""adicionado campo upload no termo

Revision ID: b589595603b6
Revises: c4a168d78f2a
Create Date: 2025-05-06 16:14:15.212951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b589595603b6'
down_revision = 'c4a168d78f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termo', schema=None) as batch_op:
        batch_op.drop_column('arquivo')

    # ### end Alembic commands ###
