"""fixando algumas vacina e as dose

Revision ID: b79662e59099
Revises: 9cfd84b28acd
Create Date: 2025-05-05 13:52:11.203053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79662e59099'
down_revision = '9cfd84b28acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
