"""Adiciona propriedades de cálculo para totais na Folha

Revision ID: c196921b86ca
Revises: fix_curso_duracao
Create Date: 2025-05-13 19:40:43.687492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c196921b86ca'
down_revision = 'fix_curso_duracao'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
