"""alterado relacionamentofolha para classe PessoaFolha

Revision ID: c2d6dc6763cd
Revises: a8868105d9f4
Create Date: 2025-05-06 17:18:14.960552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d6dc6763cd'
down_revision = 'a8868105d9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
