"""add campo upload e select definido para exames.

Revision ID: c4e83c2ab377
Revises: b79662e59099
Create Date: 2025-05-05 14:22:48.102826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e83c2ab377'
down_revision = 'b79662e59099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
