"""corrigido relacionamentos com overlaps e nullable id

Revision ID: dba2faf92e39
Revises: 3abf98a34910
Create Date: 2025-05-06 17:46:43.340218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba2faf92e39'
down_revision = '3abf98a34910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
