"""corrigido relacionamento pessoa folha com id nullable

Revision ID: ea603b00e98a
Revises: c2d6dc6763cd
Create Date: 2025-05-06 17:40:49.324436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea603b00e98a'
down_revision = 'c2d6dc6763cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa_folha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa_folha', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
