"""remover setor de pessoa

Revision ID: ec3ff682bcb6
Revises: 5233c47a47ad
Create Date: 2025-05-05 12:26:15.234983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3ff682bcb6'
down_revision = '5233c47a47ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_constraint('pessoa_setor_id_fkey', type_='foreignkey')
        batch_op.drop_column('setor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pessoa_setor_id_fkey', 'setor', ['setor_id'], ['id'])

    # ### end Alembic commands ###
