"""alterado PessoFolha id

Revision ID: ee75417bdbb7
Revises: 2fff14beb459
Create Date: 2025-05-06 19:03:00.376299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee75417bdbb7'
down_revision = '2fff14beb459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
